print("------------------------------")
print("Welcome to Lucubel Shop")
print("------------------------------")
print("Water     x", 3, 10,"THB -", 3*10, "THB")
print("Banana    x", 2, 15,"THB -", 2*15, "THB")
print("Mango     x", 4, 19,"THB -", 4*19, "THB")
print("Apple     x", 7, 14,"THB -", 7*14, "THB")
print("Pineapple x", 2, 40,"THB -", 2*40, "THB")
print("Coconut   x", 4, 20,"THB -", 4*20, "THB")
print("------------------------------")
print("Total :", (3*10)+(2*15)+(4*19)+(7*14)+(2*40)+(4*20), "THB")
print("Thank You : Lucibel Shop")